package ma.fstm.ilisi2.projects.biblio.model.bo;
// Generated 13 mars 2023 18:19:30 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Adherent generated by hbm2java
 */
@Entity
@Table(name="ADHERENT"
    ,schema="HR"
)
public class Adherent  implements java.io.Serializable {


     private Integer idClient;
     private String nom;
     private String prenom;
     private String cin;
     private Set<Emprunt> emprunts = new HashSet<>(0);

    public Adherent() {
    }

	
    public Adherent(String cin) {
        this.cin = cin;
    }
    public Adherent(Integer idClient, String nom, String prenom, String cin) {
        this.nom = nom;
        this.prenom = prenom;
        this.cin = cin;
        this.idClient = idClient;
    }
    public Adherent(String nom, String prenom, String cin) {
       this.nom = nom;
       this.prenom = prenom;
       this.cin = cin;
    }
    public Adherent(String nom, String prenom, String cin, Set<Emprunt> emprunts) {
       this.nom = nom;
       this.prenom = prenom;
       this.cin = cin;
       this.emprunts = emprunts;
    }
   
     @Id

    
    @Column(name="ID_CLIENT", unique=true, nullable=false, precision=22, scale=0)
     @SequenceGenerator(name="CLIENT_SEQ",sequenceName="CLIENT_SEQ", allocationSize = 1)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CLIENT_SEQ")
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }

    
    @Column(name="NOM", length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRENOM", length=20)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="CIN", nullable=false, length=20)
    public String getCin() {
        return this.cin;
    }
    
    public void setCin(String cin) {
        this.cin = cin;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="adherent")
    public Set<Emprunt> getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set emprunts) {
        this.emprunts = emprunts;
    }




}


