package ma.fstm.ilisi2.projects.biblio.model.bo;
// Generated 13 mars 2023 18:19:30 by Hibernate Tools 4.3.1



import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;


/**
 * Exemplaire generated by hbm2java
 */
@Entity
@Table(name="EXEMPLAIRE"
    ,schema="HR"
)
public class Exemplaire  implements java.io.Serializable {


     private Integer idExemp;
     private Livre livre;
     private Set<Emprunt> emprunts = new HashSet<>(0);

    public Exemplaire() {
    }


    public Exemplaire(Integer idExemp, Livre livre) {
        this.livre = livre;
        this.idExemp = idExemp;
    }
    public Exemplaire(Livre livre) {
        this.livre = livre;
    }
    public Exemplaire(Integer idExemp, Livre livre, Set<Emprunt> emprunts) {
        this.livre = livre;
        this.emprunts = emprunts;
        this.idExemp = idExemp;
    }
    public Exemplaire(Livre livre, Set<Emprunt> emprunts) {
       this.livre = livre;
       this.emprunts = emprunts;
    }
   
     @Id
     @Column(name="ID_EXEMP", unique=true, nullable=false, precision=22, scale=0)
     @SequenceGenerator(name="EXEMPLAIRE_SEQ",sequenceName="EXEMPLAIRE_SEQ", allocationSize = 1)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "EXEMPLAIRE_SEQ")
     //@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "EXEMPLAIRE_SEQ")
    public Integer getIdExemp() {
        return this.idExemp;
    }
    
    public void setIdExemp(Integer idExemp) {
        this.idExemp = idExemp;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_LIVRE", nullable=false)
    public Livre getLivre() {
        return this.livre;
    }
    
    public void setLivre(Livre livre) {
        this.livre = livre;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="exemplaire")
    public Set<Emprunt> getEmprunts() {
        return this.emprunts;
    }
    
    public void setEmprunts(Set emprunts) {
        this.emprunts = emprunts;
    }




}


